fantasyBlog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):

    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField("Post")

fantasyBlog/blog_posts/views.py
from flask import render_template,url_for,redirect,request,Blueprint, abort
from flask_login import login_required, current_user
from fantasyBlog import db
from fantasyBlog.models import BlogPost
from fantasyBlog.blog_posts.forms import BlogPostForm


blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()
    
    if form.validate_on_submit():
        blog_post = BlogPost(title=form.title.data,
                             content=form.content.data,
                             user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()

        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)

@blog_posts.route('/<int:post_id>')
def blog_post(post_id):
    
    blog_post = BlogPost.query.get_or_404(post_id)
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post)

@blog_posts.route("/<int:post_id>/edit", methods=['GET', 'POST'])
@login_required
def edit(post_id):
    blog_post = BlogPost.query.get_or_404(post_id)
    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.content = form.content.data
        db.session.commit()
        return redirect(url_for('blog_posts.blog_post', post_id=blog_post.id))
    
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.content.data = blog_post.content
    return render_template('create_post.html', title='Update',
                           form=form)


@blog_posts.route("/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    blog_post = BlogPost.query.get_or_404(post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    return redirect(url_for('core.index'))

fantasyBlog/users/views.py
# users/views.py
from flask import render_template,url_for,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from fantasyBlog import db
from fantasyBlog.models import User, BlogPost
from fantasyBlog.users.forms import RegistrationForm,LoginForm,UpdateUserForm

users = Blueprint('users',__name__)

@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)

@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(username=form.username.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("core.index"))

@users.route('/settings',methods=['GET','POST'])
@login_required
def settings():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.avatar.data:
            picture = form.avatar.data
            current_user.avatar = picture

        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.about = form.about.data
        avatar = form.avatar.data
        db.session.commit()
        return redirect(url_for('users.settings'))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.about.data = current_user.about
        form.avatar.data = current_user.avatar

    avatar = url_for('static',filename='avatars/'+current_user.avatar)
    return render_template('settings.html',avatar=avatar,form=form)


@users.route('/<username>')
def account(username):
    page = request.args.get('page', 1, type=int) #cycling through pages of posts
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    return render_template('account.html', blog_posts=blog_posts, user=user)

fantasyBlog/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="post-container">
    <div class="title" id="title-username">{{user.username}}</div>
    <img class="img-avatar" src="{{ url_for('static', filename='avatars/' + user.avatar) }}">
  </div>
  <div class="post-container">
    <div class="title" id="title-username">About author:</div>
    <div class="post-text-body"> {{user.about}} </div>
  </div>

  <div class="title" id="title-posts">Posts of this user:</div>
  <hr />
  {% for post in blog_posts.items %}

  <a href="{{ url_for('blog_posts.blog_post', post_id=post.id) }}">
    <div class="post-text-title">{{ post.title }}</div>
  </a>
  <div class="post-text-body">Published on: {{ post.date.strftime('%Y-%m-%d') }}</div>
  <div class="post-text-body">{{post.content[:100]|safe}}...</div>
  <hr>
  {% endfor %}


<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if blog_posts.page == page_num %}
    <li class="page-item disabled">
      <a class="page-link"
        href="{{ url_for('users.account', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
    </li>
    {% else %}
    <li class="page-item"><a class="page-link"
        href="{{ url_for('users.account', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
    {% endif %}
    {% endfor %}
</nav>
</div>
{% endblock content %}

fantasyBlog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Marcellus&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.js"></script>
    <link rel="stylesheet" type="text/css" href="./../static/styles.css">
    <title>fantasyBlog</title>
</head>

<body>
    <header>
        <div id="header-container">
            <div id="title-fantasy" class="title">Fantasy Blog</a></div>
            <div id="container-right">
                <a href="{{url_for('core.index')}}">
                    <div class="link">Home |</div>
                </a>
                {% if current_user.is_authenticated %}
                <a href="{{url_for('blog_posts.create_post')}}">
                    <div class="link">Create a post |</div>
                </a>
                <a href="{{url_for('users.settings')}}">
                    <div class="link">Change Settings |</div>
                </a>
                <a href="{{url_for('users.logout')}}">
                    <div class="link link-last">Log Out</div>
                </a>
                {% else %}
                <a href="{{url_for('users.login')}}">
                    <div class="link">Log In |</div>
                </a>
                <a href="{{url_for('users.register')}}">
                    <div class="link link-last">Register</div>
                </a>
                {% endif %}
            </div>
    </header>
    {% block content %}

    {% endblock %}
</body>
</html>

fantasyBlog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="post-container">
    <div class="title" id="title-username">{{ post.title }} <div class="post-text-body">By: {{ post.author.username }}|
        {{ post.date.strftime('%Y-%m-%d') }}</div>
      <img class="img-avatar" src="{{ url_for('static', filename='avatars/' + post.author.avatar) }}">
    </div>
  </div>
  <div class="post-text-body">
    <p>{{post.content|safe}}</p>
  </div>
  {% if post.author == current_user %}
  <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
  <a class="btn btn-outline-success" href="{{ url_for('blog_posts.edit', post_id=post.id) }}">Edit</a>

  {% endif %}
</div>
<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post Modal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete this blog post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
        <form action="{{ url_for('blog_posts.delete_post', post_id=post.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

fantasyBlog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="post-container" id="single-line">
        <div class="title" id="title-username">Write your review:</div>
    </div>
    <form class="form-group" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label(class="form-control-label") }}
            {{ form.title(class="form-control form-control-lg ") }}
        </div>

        <div class="form-group">
            {{ form.content.label(class="form-control-label") }}
            {{ form.content(class="form-control form-control-lg", rows="20", cols="50", id="summernote") }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-success") }}
        </div>
    </form>
    <script>
            $('#summernote').summernote({
              placeholder: 'Write your content here',
              tabsize: 2,
              height: 500
            });
    </script>
</div>

{% endblock content %}

fantasyBlog/templates/index.html
{% extends "base.html" %}

{% block content %}

  <div class="post-background" id="post-container-0"></div>
  <div class="container">
  <div class="row">
    <div class="col-s-12 col-md-9">
      <div class="post">
        {% for post in blog_posts.items %}
        <div class="post-container">
          <a class="" href="{{ url_for('blog_posts.blog_post', post_id=post.id) }}">
            <div class="post-text-title">{{ post.title }}
          </a>
          <img class="img-avatar img-avatar-home"
            src="{{ url_for('static', filename='avatars/' + post.author.avatar) }}"></div>
        <div class="post-text-body"> {{ post.content[:500]|safe }}... </div>
        <hr />
        <div class="post-text-body">By:<a href="{{ url_for('users.account', username=post.author.username) }}">
            {{ post.author.username }}</a>| {{ post.date.strftime('%Y-%m-%d') }}</div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="col-s-12 col-md-3">
    <div class="post post-sidebar">
      <div class="post-text-title"> Blog Search </div>
      <hr />
      <form method="POST" style="display: inline;" action="{{ url_for('core.index') }}" name="search">
        {{ searchForm.hidden_tag() }}
        {{ searchForm.search(size=20)}}
        <button type="submit" id="submitButton">
          <img src="https://img.icons8.com/ios-glyphs/30/000000/search.png">
        </button>
      </form>
    </div>
  </div>
</div>
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if blog_posts.page == page_num %}
    <li class="page-item disabled">
      <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
    </li>
    {% else %}
    <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
    </li>
    {% endif %}
    {% endfor %}
</nav>
</div>

{% endblock %}

fantasyBlog/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="post-container col-s-12 col-md-4">
    <form method="POST">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.username.label}}
            {{form.username(class="form-control")}}
        </div>
        <div class="form-group">
            {{form.password.label}}
            {{form.password(class="form-control")}}
        </div>
        <div class="form-group">
            {{form.submit(type="submit", class="btn btn-outline-success")}}
        </div>
    </form>
</div>
{% endblock %}

fantasyBlog/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="post-container col-s-12 col-md-4">
    <form method="POST">
        <div class="row form-group">
            {{form.hidden_tag()}}
        </div>
        <div class="form-group">
            {{form.email.label}}
            {{form.email(class="form-control")}}
        </div>
        <div class="form-group">
            {{form.username.label}}
            {{form.username(class="form-control")}}
        </div>
        <div class="form-group">
            {{form.password.label}}
            {{form.password(class="form-control")}}
        </div>
        <div class="form-group">
            {{form.confirm.label}}
            {{form.confirm(class="form-control")}}
        </div>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-success")}}
        </div>
    </form>
</div>
{% endblock %}

fantasyBlog/templates/settings.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="post-container">
    <div class="title" id="title-username">Update settings</div>
    <img class="img-avatar" src="{{url_for('static',filename='avatars/'+current_user.avatar)}}">
  </div>
  <form method="POST" action="" enctype="multipart/form-data">
    {{form.hidden_tag()}}
    <div class="form-group">
      {{form.username.label(class="form-group")}}
      {{form.username(class="form-control")}}
    </div>

    <div class="form-group">
      {{form.email.label(class="form-group")}}
      {{form.email(class="form-control")}}
    </div>
    <div class="form-group">
      {{form.about.label(class="form-group")}}
      {{form.about(class="form-control",  rows="6") }}
    </div>
    <div class="form-group">
      {{form.avatar.label(class="form-group")}}
      {{form.avatar(class="form-control")}}
    </div>

    <div class="form-group">
      {{form.submit(class="btn btn-outline-success")}}
    </div>
  </form>
</div>

{% endblock %}